@startuml
start
:获取请假信息(员工, 请假日期, 请假时长);
:验证请假参数;
if (判断是否为育儿假类型) then (true)
:获取现有育儿假天数;
if (现有育儿假数 >= 请假天数) then (true)
if (请假日期 > 当前日期) then (true)
:保存到假期记录表中;
else (false)
:按(有效期和创建时间并顺序)获取育儿假的列表;
:请假天数 = 请假天数;
:循环扣减;
if ( 剩余假期余额 > 请假天数) then (true)
:剩余假期余额 = 0 ;
:请假天数 = 请假天数 - 剩余假期余额;
:更新育儿假表;
:更新育儿假日志表;
:更新假期余额;
else (false)
:剩余假期余额 = 剩余假期余额 - 请假天数;
:更新育儿假表;
:更新育儿假日志表;
:更新假期余额;
:直接扣减,并退出循环;
endif
endif
else (false)
:不是育儿假期;
end
endif
else (false)
:假期类型不对;
end
endif
stop
@enduml