@startuml
start
:ps销假信息;
:验证销假参数;
if(销假类型是否为育儿假类型)then(true)
:循环销假列表;
:获取待销假的天数;
if (销假天数 大于 0) then (true)
:获取按照(过期时间和创建时间)倒叙查询育儿假列表;
:待销假天数 = 待销假天数;
:循环育儿假列表;
if(判断该用户的孩子是否有效)then(true)
if (已用育儿假 > 0 && 待销假天数 > 0 ) then (true)
if(待销假天数 > 已用天数) then (true)
:待销假天数 = 待销假天数 - 已用育儿假;
:已用天数 = 0;
:剩余假期天数 = 剩余假期天数 + 已用假期天数;
:新增销育儿假记录,并更新育儿假表,更新假期余额表;
else(false)
:已用天数 = 已用天数 - 销假天数 ;
:剩余假期天数 = 剩余假期天数 + 销假天数;
:新增销育儿假记录,并更新育儿假表,更新假期余额表;
:退出循环;
endif
else (false)
:该数据没有用过育儿假, 请到销到下一条数据上;
endif
else (false)
:获取该孩子的请假记录;
:循环请假记录,将假期请假数据退回;
endif
else (false)
:无销假信息;
endif
else (false)
:假期类型不是育儿假;
end
endif
stop
@enduml